# Generated by Django 4.0.6 on 2022-07-10 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0002_rename_instituiton_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره رهگیری')),
                ('transaction_type', models.IntegerField(choices=[(0, 'واریز'), (1, 'برداشت')], verbose_name='نوع تراکنش')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار'), (1, 'تایید شده'), (2, 'رد شده')], verbose_name='وضعیت')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
