# Generated by Django 4.0.6 on 2022-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_depositrequest_alter_usertransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepositrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
