# Generated by Django 4.0.6 on 2022-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_userdepositrequest_unique_user_deposit_request'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdepositrequest',
            name='unique_user_deposit_request',
        ),
        migrations.AddConstraint(
            model_name='userdepositrequest',
            constraint=models.UniqueConstraint(fields=('user', 'deposit_request'), name='unique_user_deposit_request'),
        ),
    ]
