# Generated by Django 4.0.6 on 2022-07-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_remove_userdepositrequest_unique_user_deposit_request_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdepositrequest',
            name='unique_user_deposit_request',
        ),
    ]
