# Generated by Django 4.0.6 on 2022-07-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instituiton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.instituiton'),
        ),
    ]
