# Generated by Django 4.0.6 on 2022-07-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_instituiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instituiton',
            new_name='institution',
        ),
    ]
