# Generated by Django 4.0.6 on 2022-07-10 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_instituiton_user_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(verbose_name='مقدار')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='شماره رهگیری')),
                ('transaction_type', models.IntegerField(choices=[(0, 'واریز'), (1, 'برداشت')], verbose_name='نوع تراکنش')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار'), (1, 'تایید شده'), (2, 'رد شده')], verbose_name='وضعیت')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.userwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
