# Generated by Django 4.0.6 on 2022-07-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userwallet_userwallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.DeleteModel(
            name='UserWalletTransaction',
        ),
    ]
