# Generated by Django 4.0.6 on 2022-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userwallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد سهم'),
        ),
    ]
