# Generated by Django 4.0.6 on 2022-07-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_remove_userdepositrequest_unique_user_deposit_request'),
        ('users', '0006_user_deposit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='institution.institution'),
        ),
    ]
